# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api/
###

# ========== Todo Routes ==========

@todo = {{baseUrl}}/todo
@todoId = {{GetTodos.response.body.0._id}}

# @name GetTodos
GET {{todo}}
###




# @name CreateTodo
POST {{todo}}
Content-Type: application/json

{
  "text": "New text Here",
  "listId": "{{listId}}"
}
###



# @name UpdateTodoById
PATCH {{todo}}/{{todoId}}
Content-Type: application/json

{
  "text": "ddada"
}
###



# @name DeleteCompletedTodos
DELETE {{todo}}/completed
###

# ========== List Routes ==========

@list = {{baseUrl}}/list

# @name CreateList
POST {{list}}
Content-Type: application/json

{
  "title": "New List"
}
###


# @name GetLists
GET {{list}}
###

@listId = {{CreateList.response.body._id}}


# @name RenameList
PATCH {{list}}/{{listId}}
Content-Type: application/json

{
  "title": "Renamed List"
}
###



# @name DeleteList
DELETE {{list}}/{{listId}}
###


# ========== Auth Routes ==========

@auth = {{baseUrl}}/auth

POST {{auth}}/register
Content-Type: application/json

{
  "username":"shaken",
  "password":"password123"
}
###

POST {{auth}}/login
Content-Type: application/json

{
  "username":"shaken",
  "password":"password123"
}
###